{% set name = "conftrak" %}
{% set version = "0.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # TODO: update the MANIFEST.in file to include the missing files in the sdist
  # distribution, e.g.  `requirements.txt` and `LICENSE` and then the PyPI
  # sources can be used.
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/conftrak-{{ version }}.tar.gz
  url: https://github.com/NSLS-II/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d2eca29cdb138320991a6cd131066bb0a22ce982337e841774ceff53d51991e7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - doct
    - jsonschema
    - pymongo
    - pyyaml
    - requests
    - tornado >=5
    - ujson

test:
  imports:
    - conftrak
    - conftrak.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hhslepicka/conftrak.git
  summary: A light-weight beamline configuration and parameters storage and tracker
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JunAishima
    - mrakitin
